"""SearXNG lifecycle.

The user should never have to think about this. We generate a settings file,
start a container bound to localhost on a free port, wait for it to answer, and
(in ephemeral mode) stop it when the run ends. If a SearXNG is already reachable
we leave it alone.

Three settings matter and all three are wrong by default:
  * search.formats must include `json` -- otherwise every API call returns 403
  * server.limiter must be off -- otherwise our own requests get bot-blocked
  * server.secret_key must be set -- otherwise the container refuses to start
"""

from __future__ import annotations

import contextlib
import os
import secrets
import shutil
import socket
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterator

import httpx

from .config import CONTAINER_NAME, SEARXNG_IMAGE, Config, config_dir

WINDOWS_RUNTIME_PATHS = [
    r"C:\Program Files\Docker\Docker\resources\bin\docker.exe",
    r"C:\Program Files\RedHat\Podman\podman.exe",
]


class SearxngError(RuntimeError):
    pass


@dataclass
class Runtime:
    name: str  # "docker" | "podman"
    binary: str


def find_runtime(preferred: str = "") -> Runtime | None:
    candidates = [preferred] if preferred else ["docker", "podman"]
    for name in candidates:
        if not name:
            continue
        found = shutil.which(name)
        if found:
            return Runtime(name=name, binary=found)
    for path in WINDOWS_RUNTIME_PATHS:
        if Path(path).exists():
            return Runtime(name=Path(path).stem, binary=path)
    return None


def _run(runtime: Runtime, *args: str, timeout: int = 60) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [runtime.binary, *args],
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )


def runtime_ready(runtime: Runtime) -> tuple[bool, str]:
    """Is the daemon actually up? On Windows the binary exists long before it is."""
    try:
        result = _run(runtime, "info", "--format", "{{.ServerVersion}}", timeout=20)
    except (subprocess.TimeoutExpired, OSError) as error:
        return False, str(error)
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip().splitlines()
        return False, detail[-1] if detail else "daemon not responding"
    return True, result.stdout.strip()


def free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def settings_dir() -> Path:
    return config_dir() / "searxng"


def ensure_settings(force: bool = False) -> Path:
    """Write settings.yml if missing. The secret key is generated once and kept."""
    directory = settings_dir()
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "settings.yml"
    if path.exists() and not force:
        return path
    secret = secrets.token_hex(32)
    path.write_text(
        "\n".join(
            [
                "# Generated by lesstokenmoresearch. Safe to edit; delete to regenerate.",
                "use_default_settings: true",
                "",
                "general:",
                "  debug: false",
                '  instance_name: "lesstokenmoresearch"',
                "  donation_url: false",
                "",
                "server:",
                f'  secret_key: "{secret}"',
                "  limiter: false",
                "  image_proxy: false",
                "",
                "search:",
                "  safe_search: 0",
                '  autocomplete: ""',
                "  formats:",
                "    - html",
                "    - json",
                "",
                "ui:",
                "  static_use_hash: true",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return path


def probe(url: str, timeout: float = 3.0) -> bool:
    """Does a working SearXNG with JSON enabled answer at this URL?"""
    base = url.rstrip("/")
    try:
        response = httpx.get(
            f"{base}/search",
            params={"q": "ping", "format": "json"},
            timeout=timeout,
            headers={"accept": "application/json"},
        )
    except httpx.HTTPError:
        return False
    if response.status_code != 200:
        return False
    try:
        response.json()
    except ValueError:
        return False
    return True


def container_state(runtime: Runtime) -> str:
    """running | stopped | absent"""
    result = _run(runtime, "ps", "-a", "--filter", f"name=^{CONTAINER_NAME}$", "--format", "{{.State}}")
    state = result.stdout.strip().splitlines()
    if not state:
        return "absent"
    return "running" if state[0].startswith("running") else "stopped"


def container_url(runtime: Runtime) -> str | None:
    result = _run(runtime, "port", CONTAINER_NAME, "8080/tcp")
    line = result.stdout.strip().splitlines()
    if not line:
        return None
    mapping = line[0].strip()
    port = mapping.rsplit(":", 1)[-1]
    if not port.isdigit():
        return None
    return f"http://127.0.0.1:{port}"


def has_image(runtime: Runtime) -> bool:
    result = _run(runtime, "images", "-q", SEARXNG_IMAGE)
    return bool(result.stdout.strip())


def pull_image(runtime: Runtime, on_line: Callable[[str], None] | None = None) -> None:
    process = subprocess.Popen(
        [runtime.binary, "pull", SEARXNG_IMAGE],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert process.stdout is not None
    for line in process.stdout:
        if on_line:
            on_line(line.rstrip())
    if process.wait() != 0:
        raise SearxngError(f"could not pull {SEARXNG_IMAGE}")


def start_container(runtime: Runtime, port: int) -> str:
    """Create, copy the settings in, then start.

    Deliberately no bind mount. Host path translation is the single most
    fragile part of running containers across Docker Desktop, Podman on
    Windows, WSL and plain Linux -- `cp` into a created container behaves
    identically everywhere.
    """
    settings = ensure_settings()
    _run(runtime, "rm", "-f", CONTAINER_NAME)

    created = _run(
        runtime,
        "create",
        "--name",
        CONTAINER_NAME,
        "-p",
        f"127.0.0.1:{port}:8080",
        "-e",
        f"SEARXNG_BASE_URL=http://localhost:{port}/",
        "-e",
        "SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml",
        SEARXNG_IMAGE,
        timeout=120,
    )
    if created.returncode != 0:
        raise SearxngError((created.stderr or created.stdout).strip()[:400])

    copied = _run(runtime, "cp", str(settings), f"{CONTAINER_NAME}:/etc/searxng/settings.yml", timeout=60)
    if copied.returncode != 0:
        _run(runtime, "rm", "-f", CONTAINER_NAME)
        raise SearxngError(f"could not install settings into the container: {(copied.stderr or copied.stdout)[:300]}")

    started = _run(runtime, "start", CONTAINER_NAME, timeout=120)
    if started.returncode != 0:
        detail = (started.stderr or started.stdout).strip()[:400]
        _run(runtime, "rm", "-f", CONTAINER_NAME)
        raise SearxngError(detail)
    return f"http://127.0.0.1:{port}"


def wait_ready(url: str, timeout: float = 90.0, on_tick: Callable[[float], None] | None = None) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if probe(url, timeout=2.0):
            return
        if on_tick:
            on_tick(deadline - time.time())
        time.sleep(1.0)
    raise SearxngError(f"SearXNG did not become ready within {timeout:.0f}s")


def stop_container(runtime: Runtime) -> bool:
    if container_state(runtime) == "absent":
        return False
    _run(runtime, "rm", "-f", CONTAINER_NAME, timeout=60)
    return True


def logs(runtime: Runtime, lines: int = 40) -> str:
    result = _run(runtime, "logs", "--tail", str(lines), CONTAINER_NAME)
    return (result.stdout + result.stderr).strip()


@contextlib.contextmanager
def searxng(config: Config, report: Callable[[str, str], None] | None = None) -> Iterator[str]:
    """Yield a working SearXNG base URL, managing the container as configured."""

    def say(text: str, level: str = "info") -> None:
        if report:
            report(text, level)

    mode = config.search.mode

    configured = config.search.url or os.environ.get("LTMS_SEARXNG_URL", "")
    if configured and probe(configured):
        say(f"using SearXNG already running at {configured}")
        yield configured.rstrip("/")
        return

    if mode == "external":
        raise SearxngError(
            f"search.mode is 'external' but nothing answered at {configured or '(no url set)'}.\n"
            "Set search.url, or run `ltms init` to let ltms manage SearXNG itself."
        )

    runtime = find_runtime(config.search.runtime)
    if runtime is None:
        raise SearxngError(
            "No container runtime found. ltms needs Docker or Podman to run SearXNG.\n"
            "  Windows, no desktop app:  winget install RedHat.Podman\n"
            "                            podman machine init && podman machine start\n"
            "  Linux:                    https://docs.docker.com/engine/install/\n"
            "  macOS:                    brew install podman  (or Docker Desktop)\n"
            "Already run SearXNG somewhere? `ltms init` → 'external'."
        )

    ready, detail = runtime_ready(runtime)
    if not ready:
        raise SearxngError(
            f"{runtime.name} is installed but not responding ({detail}).\n"
            "Start Docker Desktop (or the docker service) and try again."
        )

    started_here = False
    if container_state(runtime) == "running":
        url = container_url(runtime)
        if url and probe(url):
            say(f"reusing warm SearXNG at {url}")
            try:
                yield url
            finally:
                if mode == "ephemeral":
                    stop_container(runtime)
                    say("stopped SearXNG")
            return
        stop_container(runtime)

    if not has_image(runtime):
        say("pulling searxng image (~250 MB, first run only)", "warn")
        pull_image(runtime, on_line=lambda line: say(line[:80]))

    port = config.search.port or free_port()
    say(f"starting SearXNG on port {port}")
    url = start_container(runtime, port)
    started_here = True
    try:
        wait_ready(url)
    except SearxngError:
        tail = logs(runtime)
        stop_container(runtime)
        raise SearxngError(f"SearXNG failed to start.\n{tail[-600:]}")

    say("SearXNG ready")
    try:
        yield url
    finally:
        if started_here and mode == "ephemeral":
            stop_container(runtime)
            say("stopped SearXNG")
